version: 2
updates:
  # Security updates for Poetry dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix"
      include: scope

  # Regular updates for Poetry dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
