# Configuration for pre-commit hooks (see https://pre-commit.com/).
# Eventually the hooks described here will be run as tests before merging each PR.

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch  # main and master commits restricted
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types:
          - "markdown"

  - repo: local
    hooks:
      - id: ruff
        name: Ruff Python code linting
        entry: ruff
        language: system
        types_or: [ python, pyi ]
        args: [ --fix ]

      - id: black
        name: black Python code formatting
        entry: black
        language: system
        types_or: [ python, pyi ]

      - id: isort
        name: isort Python import sorting
        entry: isort
        language: system
        types_or: [ python, pyi ]

      - id: ruff-format
        name: Ruff Python code formatting
        entry: ruff
        language: system
        types_or: [ python, pyi ]
