[tox]
envlist = py310, py311, py312, py313
isolated_build = true

[testenv]
description = Run tests, linting, and security checks
allowlist_externals = uv

commands_pre =
    uv pip install --upgrade pip
    uv pip install -e . --group dev

commands =
    pytest tests/integration --no-cov
